2020-10-19 01:49:36.894 [error] <0.756.0> CRASH REPORT Process <0.756.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"sec-fetch-dest">> => <<"empty">>,<<"sec-fetch-mode">> => <<"no-cors">>,...},...}},...},...},...},...},...},...}
2020-10-19 01:49:36.895 [error] <0.756.0> Cowboy stream 1 with ranch listener 'Elixir.GetmoreApiChallengeWeb.Endpoint.HTTP' and connection process <0.755.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"sec-fetch-dest">> => <<"empty">>,<<"sec-fetch-mode">> => <<"no-cors">>,...},...}},...},...},...},...},...}
2020-10-19 01:49:42.840 [error] <0.759.0> CRASH REPORT Process <0.759.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US...">>,...},...}},...},...},...},...},...},...}
2020-10-19 01:49:42.840 [error] <0.759.0> Cowboy stream 1 with ranch listener 'Elixir.GetmoreApiChallengeWeb.Endpoint.HTTP' and connection process <0.758.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,e...">>,...},...}},...},...},...},...},...}
2020-10-19 01:49:43.009 [error] <0.761.0> CRASH REPORT Process <0.761.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"grafana_session=...">>,...},...}},...},...},...},...},...},...}
2020-10-19 01:49:43.009 [error] <0.761.0> Cowboy stream 2 with ranch listener 'Elixir.GetmoreApiChallengeWeb.Endpoint.HTTP' and connection process <0.758.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"grafana_session=56...">>,...},...}},...},...},...},...},...}
2020-10-19 02:16:14.867 [error] <0.724.0> gen_server 'Elixir.RPX.AMQP.Server' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<>>,position => 0,token => nil} in 'Elixir.Jason':'decode!'/2 line 78
2020-10-19 02:16:14.868 [error] <0.724.0> CRASH REPORT Process 'Elixir.RPX.AMQP.Server' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<>>,position => 0,token => nil} in 'Elixir.Jason':'decode!'/2 line 78
2020-10-19 02:16:14.868 [error] <0.548.0> Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.RPX.AMQP.Server' started with 'Elixir.RPX.AMQP.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.724.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<>>,position => 0,token => nil} in 'Elixir.Jason':'decode!'/2 line 78 in context child_terminated
2020-10-19 02:22:17.677 [error] <0.667.0>@Elixir.GetmoreApiChallenge.Getmore:list_products CRASH REPORT Process <0.667.0> with 1 neighbours crashed with reason: call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products([])
2020-10-19 02:22:17.677 [error] <0.559.0>@Elixir.GetmoreApiChallenge.Getmore:list_products Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.RPX.AMQP.Server' started with 'Elixir.RPX.AMQP.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.630.0> exit with reason call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products([]) in context child_terminated
2020-10-19 02:23:36.268 [error] <0.642.0> gen_server <0.642.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-10-19 02:23:36.269 [error] <0.642.0> CRASH REPORT Process <0.642.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-10-19 02:23:36.270 [error] <0.641.0> Supervisor {<0.641.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:41203 -> 127.0.0.1:5672">>,1}) at <0.642.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-10-19 02:23:36.270 [error] <0.641.0> Supervisor {<0.641.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:41203 -> 127.0.0.1:5672">>,1}) at <0.642.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-19 02:28:47.063 [error] <0.542.0>@Elixir.GetmoreApiChallenge.Getmore:list_products CRASH REPORT Process <0.542.0> with 1 neighbours crashed with reason: call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products([])
2020-10-19 02:28:47.063 [error] <0.435.0>@Elixir.GetmoreApiChallenge.Getmore:list_products Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.RPX.AMQP.Server' started with 'Elixir.RPX.AMQP.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.507.0> exit with reason call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products([]) in context child_terminated
2020-10-19 02:30:32.814 [error] <0.518.0> gen_server <0.518.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-10-19 02:30:32.814 [error] <0.518.0> CRASH REPORT Process <0.518.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-10-19 02:30:32.814 [error] <0.517.0> Supervisor {<0.517.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:44777 -> 127.0.0.1:5672">>,1}) at <0.518.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-10-19 02:30:32.815 [error] <0.517.0> Supervisor {<0.517.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:44777 -> 127.0.0.1:5672">>,1}) at <0.518.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-19 02:33:34.550 [error] <0.527.0> CRASH REPORT Process <0.527.0> with 1 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"deps/ecto/lib/ecto/repo/queryable.ex:451: value `1001` in `where` cannot be cast to type :binary_id in query:\n\nfrom p0 in GetmoreApiChallenge.Getmore.Product,\n  where: p0.id == ^1001,\n  select: p0\n">>,type => binary_id,value => 1001} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 2111
2020-10-19 02:33:34.550 [error] <0.419.0> Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.RPX.AMQP.Server' started with 'Elixir.RPX.AMQP.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.491.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"deps/ecto/lib/ecto/repo/queryable.ex:451: value `1001` in `where` cannot be cast to type :binary_id in query:\n\nfrom p0 in GetmoreApiChallenge.Getmore.Product,\n  where: p0.id == ^1001,\n  select: p0\n">>,type => binary_id,value => 1001} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 2111 in context child_terminated
2020-10-19 02:59:13.521 [error] <0.526.0>@Elixir.GetmoreApiChallenge.RPX.Server:-handle_info/2-fun-0-:30 CRASH REPORT Process <0.526.0> with 1 neighbours crashed with reason: bad argument in call to erlang:apply('Elixir.GetmoreApiChallenge.Getmore', 'get_product!', 1001) in 'Elixir.GetmoreApiChallenge.RPX.Server':'-handle_info/2-fun-0-'/4 line 30
2020-10-19 02:59:13.521 [error] <0.419.0>@Elixir.GetmoreApiChallenge.RPX.Server:-handle_info/2-fun-0-:30 Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.GetmoreApiChallenge.RPX.Server' started with 'Elixir.GetmoreApiChallenge.RPX.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.491.0> exit with reason bad argument in call to erlang:apply('Elixir.GetmoreApiChallenge.Getmore', 'get_product!', 1001) in 'Elixir.GetmoreApiChallenge.RPX.Server':'-handle_info/2-fun-0-'/4 line 30 in context child_terminated
2020-10-19 03:00:42.792 [error] <0.528.0> CRASH REPORT Process <0.528.0> with 1 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    @derive ...">>,...} in 'Elixir.Jason':'encode!'/2 line 150
2020-10-19 03:00:42.792 [error] <0.419.0> Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.GetmoreApiChallenge.RPX.Server' started with 'Elixir.GetmoreApiChallenge.RPX.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.491.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    @derive ...">>,...} in 'Elixir.Jason':'encode!'/2 line 150 in context child_terminated
2020-10-19 03:08:59.205 [error] <0.502.0> gen_server <0.502.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-10-19 03:08:59.206 [error] <0.502.0> CRASH REPORT Process <0.502.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-10-19 03:08:59.206 [error] <0.501.0> Supervisor {<0.501.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:43015 -> 127.0.0.1:5672">>,1}) at <0.502.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-10-19 03:08:59.207 [error] <0.501.0> Supervisor {<0.501.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:43015 -> 127.0.0.1:5672">>,1}) at <0.502.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-19 03:16:10.429 [error] <0.551.0>@Elixir.GetmoreApiChallenge.Getmore:list_products CRASH REPORT Process <0.551.0> with 1 neighbours crashed with reason: call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products([])
2020-10-19 03:16:10.429 [error] <0.444.0>@Elixir.GetmoreApiChallenge.Getmore:list_products Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.RPX.AMQP.Server' started with 'Elixir.RPX.AMQP.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.516.0> exit with reason call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products([]) in context child_terminated
2020-10-19 03:16:21.167 [error] <0.527.0> gen_server <0.527.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-10-19 03:16:21.167 [error] <0.527.0> CRASH REPORT Process <0.527.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-10-19 03:16:21.167 [error] <0.526.0> Supervisor {<0.526.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:55221 -> 127.0.0.1:5672">>,1}) at <0.527.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-10-19 03:16:21.167 [error] <0.526.0> Supervisor {<0.526.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:55221 -> 127.0.0.1:5672">>,1}) at <0.527.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-19 13:20:37.504 [error] <0.677.0>@Elixir.GetmoreApiChallenge.Getmore:list_products CRASH REPORT Process <0.677.0> with 1 neighbours crashed with reason: call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products(nil)
2020-10-19 13:20:37.504 [error] <0.569.0>@Elixir.GetmoreApiChallenge.Getmore:list_products Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.RPX.AMQP.Server' started with 'Elixir.RPX.AMQP.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.640.0> exit with reason call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products(nil) in context child_terminated
2020-10-19 13:21:25.404 [error] <0.527.0>@Elixir.GetmoreApiChallenge.Getmore:list_products CRASH REPORT Process <0.527.0> with 1 neighbours crashed with reason: call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products(<<>>)
2020-10-19 13:21:25.404 [error] <0.419.0>@Elixir.GetmoreApiChallenge.Getmore:list_products Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.RPX.AMQP.Server' started with 'Elixir.RPX.AMQP.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.491.0> exit with reason call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products(<<>>) in context child_terminated
2020-10-19 13:21:43.068 [error] <0.525.0>@Elixir.GetmoreApiChallenge.Getmore:list_products CRASH REPORT Process <0.525.0> with 1 neighbours crashed with reason: call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products([])
2020-10-19 13:21:43.068 [error] <0.419.0>@Elixir.GetmoreApiChallenge.Getmore:list_products Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.RPX.AMQP.Server' started with 'Elixir.RPX.AMQP.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.491.0> exit with reason call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products([]) in context child_terminated
2020-10-19 13:23:10.957 [error] <0.502.0> gen_server <0.502.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-10-19 13:23:10.958 [error] <0.502.0> CRASH REPORT Process <0.502.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-10-19 13:23:10.958 [error] <0.501.0> Supervisor {<0.501.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:32845 -> 127.0.0.1:5672">>,1}) at <0.502.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-10-19 13:23:10.959 [error] <0.501.0> Supervisor {<0.501.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:32845 -> 127.0.0.1:5672">>,1}) at <0.502.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-19 13:23:26.377 [error] <0.510.0> Supervisor {<0.510.0>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(network, <0.509.0>, <<"client 127.0.0.1:37201 -> 127.0.0.1:5672">>) at undefined exit with reason shutdown in context shutdown_error
2020-10-19 13:23:49.750 [error] <0.506.0>@gen_server:call gen_server 'Elixir.RPX.AMQP.Client' terminated with reason: no such process or port in call to gen_server:call(<0.518.0>, {call,{'basic.publish',0,<<>>,<<"products">>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 246
2020-10-19 13:23:49.753 [error] <0.506.0>@gen_server:call CRASH REPORT Process 'Elixir.RPX.AMQP.Client' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.518.0>, {call,{'basic.publish',0,<<>>,<<"products">>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 246
2020-10-19 13:23:49.754 [error] <0.419.0>@gen_server:call Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.RPX.AMQP.Client' started with 'Elixir.RPX.AMQP.Client':start_link([]) at <0.506.0> exit with reason no such process or port in call to gen_server:call(<0.518.0>, {call,{'basic.publish',0,<<>>,<<"products">>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2020-10-19 13:23:49.754 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 3 neighbours exited with reason: {{noproc,{gen_server,call,[<0.518.0>,{call,{'basic.publish',0,<<>>,<<"products">>,false,false},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,<<"g1hkAA1ub25vZGVAbm9ob3N0AAACIwAAAAAAAAAA,LTU3NjQ2MDc1MjMwMzQyMjkwMw==">>,<<"amq.rabbitmq.reply-to">>,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"{\"params\":[],\"target\":\"list_products\"}">>},<0.506.0>},60000]}},{'Elixir.GenServer',call,['Elixir.RPX.AMQP.Client',{send,#{correlation_id => <<"LTU3NjQ2MDc1...">>,...},...},...]}} in 'Elixir.GenServer':call/3 line 1023
2020-10-19 13:27:54.835 [error] <0.676.0>@Elixir.GetmoreApiChallenge.Getmore:list_products CRASH REPORT Process <0.676.0> with 1 neighbours crashed with reason: call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products([])
2020-10-19 13:27:54.835 [error] <0.569.0>@Elixir.GetmoreApiChallenge.Getmore:list_products Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.RPX.AMQP.Server' started with 'Elixir.RPX.AMQP.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.640.0> exit with reason call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products([]) in context child_terminated
2020-10-19 13:28:15.873 [error] <0.652.0> gen_server <0.652.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-10-19 13:28:15.874 [error] <0.652.0> CRASH REPORT Process <0.652.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-10-19 13:28:15.874 [error] <0.651.0> Supervisor {<0.651.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:41517 -> 127.0.0.1:5672">>,1}) at <0.652.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-10-19 13:28:15.875 [error] <0.651.0> Supervisor {<0.651.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:41517 -> 127.0.0.1:5672">>,1}) at <0.652.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-19 13:29:37.103 [error] <0.526.0>@Elixir.GetmoreApiChallenge.Getmore:list_products CRASH REPORT Process <0.526.0> with 1 neighbours crashed with reason: call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products([])
2020-10-19 13:29:37.104 [error] <0.419.0>@Elixir.GetmoreApiChallenge.Getmore:list_products Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.RPX.AMQP.Server' started with 'Elixir.RPX.AMQP.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.491.0> exit with reason call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products([]) in context child_terminated
2020-10-19 13:31:29.582 [error] <0.501.0>@Elixir.GetmoreApiChallenge.RPX.Server:handle_info:25 gen_server 'Elixir.GetmoreApiChallenge.RPX.Server' terminated with reason: no function clause matching 'Elixir.GetmoreApiChallenge.RPX.Server':handle_info({#Ref<0.1640465482.4013948939.96944>,ok}, #{config => #{'__struct__' => 'Elixir.RPX.AMQP',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...},...},...}) line 25
2020-10-19 13:31:29.585 [error] <0.501.0>@Elixir.GetmoreApiChallenge.RPX.Server:handle_info:25 CRASH REPORT Process 'Elixir.GetmoreApiChallenge.RPX.Server' with 0 neighbours crashed with reason: no function clause matching 'Elixir.GetmoreApiChallenge.RPX.Server':handle_info({#Ref<0.1640465482.4013948939.96944>,ok}, #{config => #{'__struct__' => 'Elixir.RPX.AMQP',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...},...},...}) line 25
2020-10-19 13:31:29.585 [error] <0.429.0>@Elixir.GetmoreApiChallenge.RPX.Server:handle_info:25 Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.GetmoreApiChallenge.RPX.Server' started with 'Elixir.GetmoreApiChallenge.RPX.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.501.0> exit with reason no function clause matching 'Elixir.GetmoreApiChallenge.RPX.Server':handle_info({#Ref<0.1640465482.4013948939.96944>,ok}, #{config => #{'__struct__' => 'Elixir.RPX.AMQP',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...},...},...}) line 25 in context child_terminated
2020-10-19 13:32:18.461 [error] <0.640.0>@Elixir.GetmoreApiChallenge.RPX.Server:handle_info:25 gen_server 'Elixir.GetmoreApiChallenge.RPX.Server' terminated with reason: no function clause matching 'Elixir.GetmoreApiChallenge.RPX.Server':handle_info({#Ref<0.1471987200.3208904714.134255>,ok}, #{config => #{'__struct__' => 'Elixir.RPX.AMQP',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...},...},...}) line 25
2020-10-19 13:32:18.464 [error] <0.640.0>@Elixir.GetmoreApiChallenge.RPX.Server:handle_info:25 CRASH REPORT Process 'Elixir.GetmoreApiChallenge.RPX.Server' with 0 neighbours crashed with reason: no function clause matching 'Elixir.GetmoreApiChallenge.RPX.Server':handle_info({#Ref<0.1471987200.3208904714.134255>,ok}, #{config => #{'__struct__' => 'Elixir.RPX.AMQP',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...},...},...}) line 25
2020-10-19 13:32:18.464 [error] <0.569.0>@Elixir.GetmoreApiChallenge.RPX.Server:handle_info:25 Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.GetmoreApiChallenge.RPX.Server' started with 'Elixir.GetmoreApiChallenge.RPX.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.640.0> exit with reason no function clause matching 'Elixir.GetmoreApiChallenge.RPX.Server':handle_info({#Ref<0.1471987200.3208904714.134255>,ok}, #{config => #{'__struct__' => 'Elixir.RPX.AMQP',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...},...},...}) line 25 in context child_terminated
2020-10-19 13:34:48.154 [error] <0.640.0>@Elixir.GetmoreApiChallenge.RPX.Server:handle_info:25 gen_server 'Elixir.GetmoreApiChallenge.RPX.Server' terminated with reason: no function clause matching 'Elixir.GetmoreApiChallenge.RPX.Server':handle_info({#Ref<0.3236253687.524550151.62444>,ok}, #{config => #{'__struct__' => 'Elixir.RPX.AMQP',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...},...},...}) line 25
2020-10-19 13:34:48.157 [error] <0.640.0>@Elixir.GetmoreApiChallenge.RPX.Server:handle_info:25 CRASH REPORT Process 'Elixir.GetmoreApiChallenge.RPX.Server' with 0 neighbours crashed with reason: no function clause matching 'Elixir.GetmoreApiChallenge.RPX.Server':handle_info({#Ref<0.3236253687.524550151.62444>,ok}, #{config => #{'__struct__' => 'Elixir.RPX.AMQP',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...},...},...}) line 25
2020-10-19 13:34:48.157 [error] <0.569.0>@Elixir.GetmoreApiChallenge.RPX.Server:handle_info:25 Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.GetmoreApiChallenge.RPX.Server' started with 'Elixir.GetmoreApiChallenge.RPX.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.640.0> exit with reason no function clause matching 'Elixir.GetmoreApiChallenge.RPX.Server':handle_info({#Ref<0.3236253687.524550151.62444>,ok}, #{config => #{'__struct__' => 'Elixir.RPX.AMQP',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...},...},...}) line 25 in context child_terminated
2020-10-19 13:35:16.679 [error] <0.660.0> Supervisor {<0.660.0>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(network, <0.659.0>, <<"client 127.0.0.1:41925 -> 127.0.0.1:5672">>) at undefined exit with reason shutdown in context shutdown_error
2020-10-19 13:35:42.869 [error] <0.656.0>@gen_server:call gen_server 'Elixir.RPX.AMQP.Client' terminated with reason: no such process or port in call to gen_server:call(<0.668.0>, {call,{'basic.publish',0,<<>>,<<"products">>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 246
2020-10-19 13:35:42.872 [error] <0.656.0>@gen_server:call CRASH REPORT Process 'Elixir.RPX.AMQP.Client' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.668.0>, {call,{'basic.publish',0,<<>>,<<"products">>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 246
2020-10-19 13:35:42.872 [error] <0.569.0>@gen_server:call Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.RPX.AMQP.Client' started with 'Elixir.RPX.AMQP.Client':start_link([]) at <0.656.0> exit with reason no such process or port in call to gen_server:call(<0.668.0>, {call,{'basic.publish',0,<<>>,<<"products">>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2020-10-19 13:35:42.873 [error] <0.693.0> CRASH REPORT Process <0.693.0> with 1 neighbours exited with reason: {{noproc,{gen_server,call,[<0.668.0>,{call,{'basic.publish',0,<<>>,<<"products">>,false,false},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,<<"g1hkAA1ub25vZGVAbm9ob3N0AAACtQAAAAAAAAAA,LTU3NjQ2MDc1MjMwMzQyMjg0NQ==">>,<<"amq.rabbitmq.reply-to">>,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"{\"params\":[],\"target\":\"list_products\"}">>},<0.656.0>},60000]}},{'Elixir.GenServer',call,['Elixir.RPX.AMQP.Client',{send,#{correlation_id => <<"LTU3NjQ2MDc1...">>,...},...},...]}} in 'Elixir.GenServer':call/3 line 1023
2020-10-19 13:36:50.757 [error] <0.490.0>@Elixir.GetmoreApiChallenge.RPX.Server:handle_info:25 gen_server 'Elixir.GetmoreApiChallenge.RPX.Server' terminated with reason: no function clause matching 'Elixir.GetmoreApiChallenge.RPX.Server':handle_info({#Ref<0.312981493.4282646535.46466>,ok}, #{config => #{'__struct__' => 'Elixir.RPX.AMQP',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...},...},...}) line 25
2020-10-19 13:36:50.761 [error] <0.490.0>@Elixir.GetmoreApiChallenge.RPX.Server:handle_info:25 CRASH REPORT Process 'Elixir.GetmoreApiChallenge.RPX.Server' with 0 neighbours crashed with reason: no function clause matching 'Elixir.GetmoreApiChallenge.RPX.Server':handle_info({#Ref<0.312981493.4282646535.46466>,ok}, #{config => #{'__struct__' => 'Elixir.RPX.AMQP',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...},...},...}) line 25
2020-10-19 13:36:50.761 [error] <0.419.0>@Elixir.GetmoreApiChallenge.RPX.Server:handle_info:25 Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.GetmoreApiChallenge.RPX.Server' started with 'Elixir.GetmoreApiChallenge.RPX.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.490.0> exit with reason no function clause matching 'Elixir.GetmoreApiChallenge.RPX.Server':handle_info({#Ref<0.312981493.4282646535.46466>,ok}, #{config => #{'__struct__' => 'Elixir.RPX.AMQP',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...},...},...}) line 25 in context child_terminated
2020-10-19 13:39:09.929 [error] <0.491.0>@Elixir.GetmoreApiChallenge.RPX.Server:handle_info:25 gen_server 'Elixir.GetmoreApiChallenge.RPX.Server' terminated with reason: no function clause matching 'Elixir.GetmoreApiChallenge.RPX.Server':handle_info({#Ref<0.1240569201.4282646529.258866>,ok}, #{config => #{'__struct__' => 'Elixir.RPX.AMQP',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...},...},...}) line 25
2020-10-19 13:39:09.934 [error] <0.491.0>@Elixir.GetmoreApiChallenge.RPX.Server:handle_info:25 CRASH REPORT Process 'Elixir.GetmoreApiChallenge.RPX.Server' with 0 neighbours crashed with reason: no function clause matching 'Elixir.GetmoreApiChallenge.RPX.Server':handle_info({#Ref<0.1240569201.4282646529.258866>,ok}, #{config => #{'__struct__' => 'Elixir.RPX.AMQP',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...},...},...}) line 25
2020-10-19 13:39:09.934 [error] <0.419.0>@Elixir.GetmoreApiChallenge.RPX.Server:handle_info:25 Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.GetmoreApiChallenge.RPX.Server' started with 'Elixir.GetmoreApiChallenge.RPX.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.491.0> exit with reason no function clause matching 'Elixir.GetmoreApiChallenge.RPX.Server':handle_info({#Ref<0.1240569201.4282646529.258866>,ok}, #{config => #{'__struct__' => 'Elixir.RPX.AMQP',channel => #{'__struct__' => 'Elixir.AMQP.Channel',...},...},...}) line 25 in context child_terminated
2020-10-19 13:44:14.061 [error] <0.687.0>@Elixir.GetmoreApiChallenge.RPX.Server:-handle_info/2-fun-0-:30 CRASH REPORT Process <0.687.0> with 1 neighbours crashed with reason: bad argument in call to erlang:apply('Elixir.GetmoreApiChallenge.Getmore', productId, 1020) in 'Elixir.GetmoreApiChallenge.RPX.Server':'-handle_info/2-fun-0-'/4 line 30
2020-10-19 13:44:14.061 [error] <0.569.0>@Elixir.GetmoreApiChallenge.RPX.Server:-handle_info/2-fun-0-:30 Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.GetmoreApiChallenge.RPX.Server' started with 'Elixir.GetmoreApiChallenge.RPX.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.640.0> exit with reason bad argument in call to erlang:apply('Elixir.GetmoreApiChallenge.Getmore', productId, 1020) in 'Elixir.GetmoreApiChallenge.RPX.Server':'-handle_info/2-fun-0-'/4 line 30 in context child_terminated
2020-10-19 13:45:09.075 [error] <0.652.0> gen_server <0.652.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-10-19 13:45:09.076 [error] <0.652.0> CRASH REPORT Process <0.652.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-10-19 13:45:09.076 [error] <0.651.0> Supervisor {<0.651.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:59831 -> 127.0.0.1:5672">>,1}) at <0.652.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-10-19 13:45:09.077 [error] <0.651.0> Supervisor {<0.651.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:59831 -> 127.0.0.1:5672">>,1}) at <0.652.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-19 13:45:18.150 [error] <0.708.0>@Elixir.GetmoreApiChallenge.RPX.Server:-handle_info/2-fun-0-:30 CRASH REPORT Process <0.708.0> with 1 neighbours crashed with reason: bad argument in call to erlang:apply('Elixir.GetmoreApiChallenge.Getmore', getProductId, 1020) in 'Elixir.GetmoreApiChallenge.RPX.Server':'-handle_info/2-fun-0-'/4 line 30
2020-10-19 13:45:18.151 [error] <0.569.0>@Elixir.GetmoreApiChallenge.RPX.Server:-handle_info/2-fun-0-:30 Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.GetmoreApiChallenge.RPX.Server' started with 'Elixir.GetmoreApiChallenge.RPX.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.688.0> exit with reason bad argument in call to erlang:apply('Elixir.GetmoreApiChallenge.Getmore', getProductId, 1020) in 'Elixir.GetmoreApiChallenge.RPX.Server':'-handle_info/2-fun-0-'/4 line 30 in context child_terminated
2020-10-19 13:45:40.510 [error] <0.699.0> gen_server <0.699.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-10-19 13:45:40.511 [error] <0.699.0> CRASH REPORT Process <0.699.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-10-19 13:45:40.512 [error] <0.698.0> Supervisor {<0.698.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:48985 -> 127.0.0.1:5672">>,1}) at <0.699.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-10-19 13:45:40.512 [error] <0.698.0> Supervisor {<0.698.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:48985 -> 127.0.0.1:5672">>,1}) at <0.699.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-19 13:47:15.152 [error] <0.731.0>@Elixir.GetmoreApiChallenge.RPX.Server:-handle_info/2-fun-0-:30 CRASH REPORT Process <0.731.0> with 1 neighbours crashed with reason: bad argument in call to erlang:apply('Elixir.GetmoreApiChallenge.Getmore', 'get_product!', 1020) in 'Elixir.GetmoreApiChallenge.RPX.Server':'-handle_info/2-fun-0-'/4 line 30
2020-10-19 13:47:15.153 [error] <0.569.0>@Elixir.GetmoreApiChallenge.RPX.Server:-handle_info/2-fun-0-:30 Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.GetmoreApiChallenge.RPX.Server' started with 'Elixir.GetmoreApiChallenge.RPX.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.709.0> exit with reason bad argument in call to erlang:apply('Elixir.GetmoreApiChallenge.Getmore', 'get_product!', 1020) in 'Elixir.GetmoreApiChallenge.RPX.Server':'-handle_info/2-fun-0-'/4 line 30 in context child_terminated
2020-10-19 13:48:02.456 [error] <0.720.0> gen_server <0.720.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-10-19 13:48:02.457 [error] <0.720.0> CRASH REPORT Process <0.720.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-10-19 13:48:02.457 [error] <0.719.0> Supervisor {<0.719.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:43421 -> 127.0.0.1:5672">>,1}) at <0.720.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-10-19 13:48:02.458 [error] <0.719.0> Supervisor {<0.719.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:43421 -> 127.0.0.1:5672">>,1}) at <0.720.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-19 13:51:13.311 [error] <0.773.0>@Elixir.GetmoreApiChallenge.RPX.Server:-handle_info/2-fun-0-:30 CRASH REPORT Process <0.773.0> with 1 neighbours crashed with reason: bad argument in call to erlang:apply('Elixir.GetmoreApiChallenge.Getmore', get_product, #{<<"number">> => 1048}) in 'Elixir.GetmoreApiChallenge.RPX.Server':'-handle_info/2-fun-0-'/4 line 30
2020-10-19 13:51:13.311 [error] <0.569.0>@Elixir.GetmoreApiChallenge.RPX.Server:-handle_info/2-fun-0-:30 Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.GetmoreApiChallenge.RPX.Server' started with 'Elixir.GetmoreApiChallenge.RPX.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.732.0> exit with reason bad argument in call to erlang:apply('Elixir.GetmoreApiChallenge.Getmore', get_product, #{<<"number">> => 1048}) in 'Elixir.GetmoreApiChallenge.RPX.Server':'-handle_info/2-fun-0-'/4 line 30 in context child_terminated
2020-10-19 13:54:10.280 [error] <0.743.0> gen_server <0.743.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-10-19 13:54:10.280 [error] <0.743.0> CRASH REPORT Process <0.743.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-10-19 13:54:10.281 [error] <0.742.0> Supervisor {<0.742.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:35923 -> 127.0.0.1:5672">>,1}) at <0.743.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-10-19 13:54:10.281 [error] <0.742.0> Supervisor {<0.742.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:35923 -> 127.0.0.1:5672">>,1}) at <0.743.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-19 13:54:29.983 [error] <0.804.0>@Elixir.GetmoreApiChallenge.RPX.Server:-handle_info/2-fun-0-:30 CRASH REPORT Process <0.804.0> with 1 neighbours crashed with reason: bad argument in call to erlang:apply('Elixir.GetmoreApiChallenge.Getmore', get_product, #{<<"number">> => 1020}) in 'Elixir.GetmoreApiChallenge.RPX.Server':'-handle_info/2-fun-0-'/4 line 30
2020-10-19 13:54:29.984 [error] <0.569.0>@Elixir.GetmoreApiChallenge.RPX.Server:-handle_info/2-fun-0-:30 Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.GetmoreApiChallenge.RPX.Server' started with 'Elixir.GetmoreApiChallenge.RPX.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.774.0> exit with reason bad argument in call to erlang:apply('Elixir.GetmoreApiChallenge.Getmore', get_product, #{<<"number">> => 1020}) in 'Elixir.GetmoreApiChallenge.RPX.Server':'-handle_info/2-fun-0-'/4 line 30 in context child_terminated
2020-10-19 14:00:13.286 [error] <0.677.0>@Elixir.GetmoreApiChallenge.RPX.Server:-handle_info/2-fun-0-:30 CRASH REPORT Process <0.677.0> with 1 neighbours crashed with reason: bad argument in call to erlang:apply('Elixir.GetmoreApiChallenge.Getmore', get_product, <<"1020">>) in 'Elixir.GetmoreApiChallenge.RPX.Server':'-handle_info/2-fun-0-'/4 line 30
2020-10-19 14:00:13.286 [error] <0.569.0>@Elixir.GetmoreApiChallenge.RPX.Server:-handle_info/2-fun-0-:30 Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.GetmoreApiChallenge.RPX.Server' started with 'Elixir.GetmoreApiChallenge.RPX.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.640.0> exit with reason bad argument in call to erlang:apply('Elixir.GetmoreApiChallenge.Getmore', get_product, <<"1020">>) in 'Elixir.GetmoreApiChallenge.RPX.Server':'-handle_info/2-fun-0-'/4 line 30 in context child_terminated
2020-10-19 14:36:44.371 [error] <0.616.0> CRASH REPORT Process <0.616.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US...">>,...},...}},...},...},...},...},...},...}
2020-10-19 14:36:44.371 [error] <0.616.0> Cowboy stream 1 with ranch listener 'Elixir.GetmoreApiChallengeWeb.Endpoint.HTTP' and connection process <0.615.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,e...">>,...},...}},...},...},...},...},...}
2020-10-19 14:36:44.533 [error] <0.618.0> CRASH REPORT Process <0.618.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...},...},...},...},...}
2020-10-19 14:36:44.533 [error] <0.618.0> Cowboy stream 2 with ranch listener 'Elixir.GetmoreApiChallengeWeb.Endpoint.HTTP' and connection process <0.615.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"keep-alive">>,...},...}},...},...},...},...},...}
2020-10-19 14:39:31.230 [error] <0.626.0> CRASH REPORT Process <0.626.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US...">>,...},...}},...},...},...},...},...},...}
2020-10-19 14:39:31.230 [error] <0.626.0> Cowboy stream 1 with ranch listener 'Elixir.GetmoreApiChallengeWeb.Endpoint.HTTP' and connection process <0.625.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,e...">>,...},...}},...},...},...},...},...}
