2020-10-29 08:25:02.687 [error] <0.333.0> gen_server <0.333.0> terminated with reason: {socket_error,timeout}
2020-10-29 08:25:02.687 [error] <0.346.0> gen_server <0.346.0> terminated with reason: {socket_error,timeout}
2020-10-29 08:25:02.687 [error] <0.329.0> gen_server <0.329.0> terminated with reason: {socket_error,timeout}
2020-10-29 08:25:02.687 [error] <0.342.0> gen_server <0.342.0> terminated with reason: {socket_error,timeout}
2020-10-29 08:25:02.965 [error] <0.329.0> CRASH REPORT Process <0.329.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-10-29 08:25:02.965 [error] <0.327.0> Supervisor {<0.327.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.328.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.329.0> exit with reason {socket_error,timeout} in context child_terminated
2020-10-29 08:25:02.965 [error] <0.327.0> Supervisor {<0.327.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.328.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.329.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-29 08:25:02.965 [error] <0.342.0> CRASH REPORT Process <0.342.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-10-29 08:25:02.965 [error] <0.312.0> CRASH REPORT Process <0.312.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-10-29 08:25:02.975 [error] <0.310.0> Supervisor {<0.310.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.311.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.312.0> exit with reason {socket_error,timeout} in context child_terminated
2020-10-29 08:25:02.976 [error] <0.310.0> Supervisor {<0.310.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.311.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.312.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-29 08:25:02.976 [error] <0.340.0> Supervisor {<0.340.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.341.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.342.0> exit with reason {socket_error,timeout} in context child_terminated
2020-10-29 08:25:02.976 [error] <0.340.0> Supervisor {<0.340.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.341.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.342.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-29 08:25:02.978 [error] <0.355.0> CRASH REPORT Process <0.355.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-10-29 08:25:02.986 [error] <0.353.0> Supervisor {<0.353.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.354.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.355.0> exit with reason {socket_error,timeout} in context child_terminated
2020-10-29 08:25:02.986 [error] <0.353.0> Supervisor {<0.353.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.354.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.355.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-29 17:13:49.717 [error] <0.322.0>@Elixir.Products.Product.HandleMessage:read_message:26 gen_server <0.322.0> terminated with reason: no function clause matching 'Elixir.Products.Product.HandleMessage':read_message(4) line 26
2020-10-29 17:13:49.732 [error] <0.322.0>@Elixir.Products.Product.HandleMessage:read_message:26 CRASH REPORT Process <0.322.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.Products.Product.HandleMessage':read_message(4) line 26
2020-10-29 17:13:49.732 [error] <0.308.0>@Elixir.Products.Product.HandleMessage:read_message:26 Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.322.0> exit with reason no function clause matching 'Elixir.Products.Product.HandleMessage':read_message(4) line 26 in context child_terminated
2020-10-29 17:13:56.584 [error] <0.337.0> gen_server <0.337.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-10-29 17:13:56.584 [error] <0.337.0> CRASH REPORT Process <0.337.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-10-29 17:13:56.584 [error] <0.336.0> Supervisor {<0.336.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:54555 -> 127.0.0.1:5672">>,1}) at <0.337.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-10-29 17:13:56.584 [error] <0.336.0> Supervisor {<0.336.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:54555 -> 127.0.0.1:5672">>,1}) at <0.337.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-29 17:13:57.431 [error] <0.343.0>@Elixir.Products.Product.HandleMessage:read_message:26 gen_server <0.343.0> terminated with reason: no function clause matching 'Elixir.Products.Product.HandleMessage':read_message(4) line 26
2020-10-29 17:13:57.431 [error] <0.343.0>@Elixir.Products.Product.HandleMessage:read_message:26 CRASH REPORT Process <0.343.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.Products.Product.HandleMessage':read_message(4) line 26
2020-10-29 17:13:57.431 [error] <0.308.0>@Elixir.Products.Product.HandleMessage:read_message:26 Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.343.0> exit with reason no function clause matching 'Elixir.Products.Product.HandleMessage':read_message(4) line 26 in context child_terminated
2020-10-29 17:15:14.697 [error] <0.354.0> gen_server <0.354.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-10-29 17:15:14.697 [error] <0.354.0> CRASH REPORT Process <0.354.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-10-29 17:15:14.697 [error] <0.353.0> Supervisor {<0.353.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:54582 -> 127.0.0.1:5672">>,1}) at <0.354.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-10-29 17:15:14.697 [error] <0.353.0> Supervisor {<0.353.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:54582 -> 127.0.0.1:5672">>,1}) at <0.354.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-29 17:15:38.147 [error] <0.323.0>@Elixir.Products.Product.HandleMessage:read_message:28 gen_server <0.323.0> terminated with reason: no function clause matching 'Elixir.Products.Product.HandleMessage':read_message(4) line 28
2020-10-29 17:15:38.162 [error] <0.323.0>@Elixir.Products.Product.HandleMessage:read_message:28 CRASH REPORT Process <0.323.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.Products.Product.HandleMessage':read_message(4) line 28
2020-10-29 17:15:38.162 [error] <0.309.0>@Elixir.Products.Product.HandleMessage:read_message:28 Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.323.0> exit with reason no function clause matching 'Elixir.Products.Product.HandleMessage':read_message(4) line 28 in context child_terminated
2020-10-29 17:16:39.772 [error] <0.323.0>@Elixir.Products.Product.HandleMessage:read_message:35 gen_server <0.323.0> terminated with reason: no function clause matching 'Elixir.Products.Product.HandleMessage':read_message(ok) line 35
2020-10-29 17:16:39.804 [error] <0.323.0>@Elixir.Products.Product.HandleMessage:read_message:35 CRASH REPORT Process <0.323.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.Products.Product.HandleMessage':read_message(ok) line 35
2020-10-29 17:16:39.804 [error] <0.309.0>@Elixir.Products.Product.HandleMessage:read_message:35 Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.323.0> exit with reason no function clause matching 'Elixir.Products.Product.HandleMessage':read_message(ok) line 35 in context child_terminated
2020-10-29 17:17:15.710 [error] <0.323.0> gen_server <0.323.0> terminated with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-wBOdFvemKjczybfQnOEdvA">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 83
2020-10-29 17:17:15.741 [error] <0.323.0> CRASH REPORT Process <0.323.0> with 0 neighbours crashed with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-wBOdFvemKjczybfQnOEdvA">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 83
2020-10-29 17:17:15.741 [error] <0.309.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.323.0> exit with reason {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-wBOdFvemKjczybfQnOEdvA">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 83 in context child_terminated
2020-10-29 17:17:31.219 [error] <0.338.0> gen_server <0.338.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-10-29 17:17:31.219 [error] <0.338.0> CRASH REPORT Process <0.338.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-10-29 17:17:31.219 [error] <0.339.0> gen_server <0.339.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.338.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-wBOdFvemKjczybfQnOEdvA">>,6,false,<<"product_consumer">>,<<>>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"4">>}},60000]}} in gen_server2:call/3 line 346
2020-10-29 17:17:31.219 [error] <0.337.0> Supervisor {<0.337.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:54645 -> 127.0.0.1:5672">>,1}) at <0.338.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-10-29 17:17:31.219 [error] <0.337.0> Supervisor {<0.337.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:54645 -> 127.0.0.1:5672">>,1}) at <0.338.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-29 18:11:27.377 [error] <0.334.0> gen_server <0.334.0> terminated with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-PvHC2lmM08UdVw1ngEeszA">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 94
2020-10-29 18:11:27.429 [error] <0.334.0> CRASH REPORT Process <0.334.0> with 0 neighbours crashed with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-PvHC2lmM08UdVw1ngEeszA">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 94
2020-10-29 18:11:27.429 [error] <0.320.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.334.0> exit with reason {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-PvHC2lmM08UdVw1ngEeszA">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 94 in context child_terminated
2020-10-29 18:12:23.423 [error] <0.349.0> gen_server <0.349.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-10-29 18:12:23.438 [error] <0.349.0> CRASH REPORT Process <0.349.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-10-29 18:12:23.438 [error] <0.348.0> Supervisor {<0.348.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49597 -> 127.0.0.1:5672">>,1}) at <0.349.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-10-29 18:12:23.438 [error] <0.350.0> gen_server <0.350.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.349.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-PvHC2lmM08UdVw1ngEeszA">>,7,false,<<"product_consumer">>,<<>>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"4">>}},60000]}} in gen_server2:call/3 line 346
2020-10-29 18:12:23.438 [error] <0.348.0> Supervisor {<0.348.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:49597 -> 127.0.0.1:5672">>,1}) at <0.349.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-29 18:13:45.295 [error] <0.364.0> gen_server <0.364.0> terminated with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-5EEfHMFZd-U_yZxfsn_F6Q">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => false,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 94
2020-10-29 18:13:45.296 [error] <0.364.0> CRASH REPORT Process <0.364.0> with 0 neighbours crashed with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-5EEfHMFZd-U_yZxfsn_F6Q">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => false,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 94
2020-10-29 18:13:45.296 [error] <0.320.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.364.0> exit with reason {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-5EEfHMFZd-U_yZxfsn_F6Q">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => false,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 94 in context child_terminated
2020-10-29 18:13:50.298 [error] <0.311.0> gen_server <0.311.0> terminated with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-Ok3nMq7QZVltXTK7OgVuBw">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 94
2020-10-29 18:13:50.313 [error] <0.311.0> CRASH REPORT Process <0.311.0> with 0 neighbours crashed with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-Ok3nMq7QZVltXTK7OgVuBw">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 94
2020-10-29 18:13:50.313 [error] <0.297.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.311.0> exit with reason {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-Ok3nMq7QZVltXTK7OgVuBw">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 94 in context child_terminated
2020-10-29 18:15:05.150 [error] <0.322.0> gen_server <0.322.0> terminated with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-RzTFOyrACK8ObntVVEyaeA">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 94
2020-10-29 18:15:05.165 [error] <0.322.0> CRASH REPORT Process <0.322.0> with 0 neighbours crashed with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-RzTFOyrACK8ObntVVEyaeA">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 94
2020-10-29 18:15:05.165 [error] <0.307.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.322.0> exit with reason {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-RzTFOyrACK8ObntVVEyaeA">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 94 in context child_terminated
2020-10-29 19:05:11.714 [error] <0.324.0> gen_server <0.324.0> terminated with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-YXIPq4-O3tlLN3CWw_UD4Q">>,content_encoding => undefined,content_type => <<"application/json">>,correlation_id => undefined,delivery_tag => 26,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 97
2020-10-29 19:05:11.730 [error] <0.324.0> CRASH REPORT Process <0.324.0> with 0 neighbours crashed with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-YXIPq4-O3tlLN3CWw_UD4Q">>,content_encoding => undefined,content_type => <<"application/json">>,correlation_id => undefined,delivery_tag => 26,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 97
2020-10-29 19:05:11.730 [error] <0.309.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.324.0> exit with reason {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-YXIPq4-O3tlLN3CWw_UD4Q">>,content_encoding => undefined,content_type => <<"application/json">>,correlation_id => undefined,delivery_tag => 26,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 97 in context child_terminated
2020-10-29 19:06:01.063 [error] <0.312.0> gen_server <0.312.0> terminated with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-gNSQv2us0A_0qXrt8FFPqA">>,content_encoding => undefined,content_type => <<"application/json">>,correlation_id => undefined,delivery_tag => 26,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 97
2020-10-29 19:06:01.079 [error] <0.312.0> CRASH REPORT Process <0.312.0> with 0 neighbours crashed with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-gNSQv2us0A_0qXrt8FFPqA">>,content_encoding => undefined,content_type => <<"application/json">>,correlation_id => undefined,delivery_tag => 26,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 97
2020-10-29 19:06:01.079 [error] <0.297.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.312.0> exit with reason {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-gNSQv2us0A_0qXrt8FFPqA">>,content_encoding => undefined,content_type => <<"application/json">>,correlation_id => undefined,delivery_tag => 26,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 97 in context child_terminated
2020-10-29 19:06:08.641 [error] <0.336.0> gen_server <0.336.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-10-29 19:06:08.641 [error] <0.336.0> CRASH REPORT Process <0.336.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-10-29 19:06:08.641 [error] <0.337.0> gen_server <0.337.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.336.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-gNSQv2us0A_0qXrt8FFPqA">>,29,false,<<"product_consumer">>,<<>>},{amqp_msg,{'P_basic',<<"application/json">>,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"{\"name\":\"S\"}">>}},60000]}} in gen_server2:call/3 line 346
2020-10-29 19:06:08.641 [error] <0.335.0> Supervisor {<0.335.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:50974 -> 127.0.0.1:5672">>,1}) at <0.336.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-10-29 19:06:08.641 [error] <0.335.0> Supervisor {<0.335.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:50974 -> 127.0.0.1:5672">>,1}) at <0.336.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-29 19:06:14.557 [error] <0.341.0> gen_server <0.341.0> terminated with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-eIc0hAT1rfBSpksxASPDLA">>,content_encoding => undefined,content_type => <<"application/json">>,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => false,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 97
2020-10-29 19:06:14.557 [error] <0.341.0> CRASH REPORT Process <0.341.0> with 0 neighbours crashed with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-eIc0hAT1rfBSpksxASPDLA">>,content_encoding => undefined,content_type => <<"application/json">>,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => false,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 97
2020-10-29 19:06:14.557 [error] <0.297.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.341.0> exit with reason {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-eIc0hAT1rfBSpksxASPDLA">>,content_encoding => undefined,content_type => <<"application/json">>,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => false,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 97 in context child_terminated
2020-10-29 19:08:46.267 [error] <0.323.0> gen_server <0.323.0> terminated with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-Mh6LfSF-i0wpH0zrPA9yyQ">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 98
2020-10-29 19:08:46.283 [error] <0.323.0> CRASH REPORT Process <0.323.0> with 0 neighbours crashed with reason: {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-Mh6LfSF-i0wpH0zrPA9yyQ">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 98
2020-10-29 19:08:46.283 [error] <0.308.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.323.0> exit with reason {badkey,tag,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-Mh6LfSF-i0wpH0zrPA9yyQ">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => true,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}} in 'Elixir.Products.Product.Consumer':consume/3 line 98 in context child_terminated
2020-10-29 19:09:38.985 [error] <0.323.0> gen_server <0.323.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-Jcplyh3SG3G76hhUxR-FNg">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => ...,...}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:09:39.001 [error] <0.323.0> CRASH REPORT Process <0.323.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-Jcplyh3SG3G76hhUxR-FNg">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => ...,...}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:09:39.001 [error] <0.308.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.323.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-Jcplyh3SG3G76hhUxR-FNg">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => ...,...}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2020-10-29 19:11:37.157 [error] <0.323.0> gen_server <0.323.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-XTf5YsD26ksxaGRYLFyo0A">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => ...,...}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:11:37.172 [error] <0.323.0> CRASH REPORT Process <0.323.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-XTf5YsD26ksxaGRYLFyo0A">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => ...,...}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:11:37.172 [error] <0.308.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.323.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.ctag-XTf5YsD26ksxaGRYLFyo0A">>,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 1,exchange => <<"product_consumer">>,expiration => undefined,headers => undefined,message_id => undefined,persistent => false,priority => undefined,redelivered => ...,...}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2020-10-29 19:21:20.233 [error] <0.323.0> gen_server <0.323.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Scrivener.Paginater',value => []} in 'Elixir.Scrivener.Paginater':'impl_for!'/1 line 1
2020-10-29 19:21:20.247 [error] <0.323.0> CRASH REPORT Process <0.323.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Scrivener.Paginater',value => []} in 'Elixir.Scrivener.Paginater':'impl_for!'/1 line 1
2020-10-29 19:21:20.247 [error] <0.308.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.323.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Scrivener.Paginater',value => []} in 'Elixir.Scrivener.Paginater':'impl_for!'/1 line 1 in context child_terminated
2020-10-29 19:25:36.608 [error] <0.330.0> gen_server <0.330.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {error,#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to en...">>,...}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:25:36.623 [error] <0.330.0> CRASH REPORT Process <0.330.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {error,#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to en...">>,...}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:25:36.623 [error] <0.315.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.330.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {error,#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to en...">>,...}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2020-10-29 19:26:24.840 [error] <0.325.0> gen_server <0.325.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {error,#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to en...">>,...}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:26:24.857 [error] <0.325.0> CRASH REPORT Process <0.325.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {error,#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to en...">>,...}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:26:24.857 [error] <0.310.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.325.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {error,#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to en...">>,...}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2020-10-29 19:27:40.047 [error] <0.325.0> gen_server <0.325.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<<"{\"entries\":[],\"page_number\":1,\"page_size\":10,\"total_entries\":0,\"total_pages\":1}">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:27:40.047 [error] <0.325.0> CRASH REPORT Process <0.325.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<<"{\"entries\":[],\"page_number\":1,\"page_size\":10,\"total_entries\":0,\"total_pages\":1}">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:27:40.063 [error] <0.310.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.325.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<<"{\"entries\":[],\"page_number\":1,\"page_size\":10,\"total_entries\":0,\"total_pages\":1}">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2020-10-29 19:28:12.237 [error] <0.325.0>@Elixir.Products.Product.Queries:get_page:13 gen_server <0.325.0> terminated with reason: no match of right hand value #{entries => [],page_number => 1,page_size => 10,total_entries => 0,total_pages => 1} in 'Elixir.Products.Product.Queries':get_page/1 line 13
2020-10-29 19:28:12.259 [error] <0.325.0>@Elixir.Products.Product.Queries:get_page:13 CRASH REPORT Process <0.325.0> with 0 neighbours crashed with reason: no match of right hand value #{entries => [],page_number => 1,page_size => 10,total_entries => 0,total_pages => 1} in 'Elixir.Products.Product.Queries':get_page/1 line 13
2020-10-29 19:28:12.259 [error] <0.310.0>@Elixir.Products.Product.Queries:get_page:13 Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.325.0> exit with reason no match of right hand value #{entries => [],page_number => 1,page_size => 10,total_entries => 0,total_pages => 1} in 'Elixir.Products.Product.Queries':get_page/1 line 13 in context child_terminated
2020-10-29 19:29:33.001 [error] <0.325.0> gen_server <0.325.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<<"{\"entries\":[],\"page_number\":1,\"page_size\":10,\"total_entries\":0,\"total_pages\":1}">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:29:33.017 [error] <0.325.0> CRASH REPORT Process <0.325.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<<"{\"entries\":[],\"page_number\":1,\"page_size\":10,\"total_entries\":0,\"total_pages\":1}">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:29:33.017 [error] <0.310.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.325.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<<"{\"entries\":[],\"page_number\":1,\"page_size\":10,\"total_entries\":0,\"total_pages\":1}">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2020-10-29 19:30:41.673 [error] <0.325.0> gen_server <0.325.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<<"{\"entries\":[],\"page_number\":1,\"page_size\":10,\"total_entries\":0,\"total_pages\":1}">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:30:41.688 [error] <0.325.0> CRASH REPORT Process <0.325.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<<"{\"entries\":[],\"page_number\":1,\"page_size\":10,\"total_entries\":0,\"total_pages\":1}">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:30:41.688 [error] <0.310.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.325.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<<"{\"entries\":[],\"page_number\":1,\"page_size\":10,\"total_entries\":0,\"total_pages\":1}">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2020-10-29 19:31:04.335 [error] <0.325.0> gen_server <0.325.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<<"{\"entries\":[],\"page_number\":1,\"page_size\":10,\"total_entries\":0,\"total_pages\":1}">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:31:04.349 [error] <0.325.0> CRASH REPORT Process <0.325.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<<"{\"entries\":[],\"page_number\":1,\"page_size\":10,\"total_entries\":0,\"total_pages\":1}">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:31:04.350 [error] <0.310.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.325.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<<"{\"entries\":[],\"page_number\":1,\"page_size\":10,\"total_entries\":0,\"total_pages\":1}">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2020-10-29 19:31:29.610 [error] <0.325.0> gen_server <0.325.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<<"\"ok\"">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:31:29.625 [error] <0.325.0> CRASH REPORT Process <0.325.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<<"\"ok\"">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2020-10-29 19:31:29.625 [error] <0.310.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.325.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {ok,<<"\"ok\"">>}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2020-10-29 20:26:59.827 [error] <0.323.0> gen_server <0.323.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => 30} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2020-10-29 20:26:59.865 [error] <0.323.0> CRASH REPORT Process <0.323.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => 30} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2020-10-29 20:26:59.865 [error] <0.308.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.323.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => 30} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in context child_terminated
2020-10-29 20:33:32.549 [error] <0.312.0> gen_server <0.312.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => 30} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2020-10-29 20:33:32.565 [error] <0.312.0> CRASH REPORT Process <0.312.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => 30} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2020-10-29 20:33:32.565 [error] <0.297.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Products.Product.Consumer' started with 'Elixir.Products.Product.Consumer':start_link([]) at <0.312.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => 30} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in context child_terminated
