2020-11-01 10:35:43.244 [error] <0.674.0>@rabbit_framing_amqp_0_9_1:encode_method_fields:1150 CRASH REPORT Process <0.674.0> with 0 neighbours crashed with reason: bad argument in rabbit_framing_amqp_0_9_1:encode_method_fields/1 line 1150
2020-11-01 10:35:43.245 [error] <0.671.0>@rabbit_framing_amqp_0_9_1:encode_method_fields:1150 Supervisor {<0.671.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.24>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.673.0>, {<<"client 127.0.0.1:59251 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.674.0> exit with reason bad argument in rabbit_framing_amqp_0_9_1:encode_method_fields/1 line 1150 in context child_terminated
2020-11-01 10:35:43.245 [error] <0.671.0> Supervisor {<0.671.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.24>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.673.0>, {<<"client 127.0.0.1:59251 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.674.0> exit with reason reached_max_restart_intensity in context shutdown
2020-11-01 10:36:25.529 [error] <0.696.0>@rabbit_framing_amqp_0_9_1:encode_method_fields:1150 CRASH REPORT Process <0.696.0> with 0 neighbours crashed with reason: bad argument in rabbit_framing_amqp_0_9_1:encode_method_fields/1 line 1150
2020-11-01 10:36:25.530 [error] <0.693.0>@rabbit_framing_amqp_0_9_1:encode_method_fields:1150 Supervisor {<0.693.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.25>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.695.0>, {<<"client 127.0.0.1:55103 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.696.0> exit with reason bad argument in rabbit_framing_amqp_0_9_1:encode_method_fields/1 line 1150 in context child_terminated
2020-11-01 10:36:25.530 [error] <0.693.0> Supervisor {<0.693.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.25>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.695.0>, {<<"client 127.0.0.1:55103 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.696.0> exit with reason reached_max_restart_intensity in context shutdown
2020-11-01 10:36:59.285 [error] <0.710.0>@rabbit_framing_amqp_0_9_1:encode_method_fields:1150 CRASH REPORT Process <0.710.0> with 0 neighbours crashed with reason: bad argument in rabbit_framing_amqp_0_9_1:encode_method_fields/1 line 1150
2020-11-01 10:36:59.285 [error] <0.707.0>@rabbit_framing_amqp_0_9_1:encode_method_fields:1150 Supervisor {<0.707.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.26>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.709.0>, {<<"client 127.0.0.1:60429 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.710.0> exit with reason bad argument in rabbit_framing_amqp_0_9_1:encode_method_fields/1 line 1150 in context child_terminated
2020-11-01 10:36:59.286 [error] <0.707.0> Supervisor {<0.707.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.26>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.709.0>, {<<"client 127.0.0.1:60429 -> 127.0.0.1:5672">>,1}, false, 1000000000) at <0.710.0> exit with reason reached_max_restart_intensity in context shutdown
2020-11-01 15:19:42.109 [error] <0.597.0> CRASH REPORT Process <0.597.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Ecto.PendingMigrationError',repo => 'Elixir.Products.Repo'},[{'Elixir.Phoenix.Ecto.CheckRepoStatus','check_pending_migrations!',2,[{file,"lib/phoenix_ecto/check_repo_status.ex"},{line,67}]},{'Elixir.Phoenix.Ecto.CheckRepoStatus','-call/2-fun-0-',3,[{file,"lib/phoenix_ecto/check_repo_status.ex"},{line,27}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,2111}]},{'Elixir.Phoenix.Ecto.CheckRepoStatus',call,...},...]},...},...},...}
2020-11-01 15:19:42.120 [error] <0.597.0> Cowboy stream 1 with ranch listener 'Elixir.ProductsWeb.Endpoint.HTTP' and connection process <0.596.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Ecto.PendingMigrationError',repo => 'Elixir.Products.Repo'},[{'Elixir.Phoenix.Ecto.CheckRepoStatus','check_pending_migrations!',2,[{file,"lib/phoenix_ecto/check_repo_status.ex"},{line,67}]},{'Elixir.Phoenix.Ecto.CheckRepoStatus','-call/2-fun-0-',3,[{file,"lib/phoenix_ecto/check_repo_status.ex"},{line,27}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,2111}]},{'Elixir.Phoenix.Ecto.CheckRepoStatus',call,...},...]},...},...}
2020-11-01 15:20:16.067 [error] <0.605.0> CRASH REPORT Process <0.605.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Ecto.PendingMigrationError',repo => 'Elixir.Products.Repo'},[{'Elixir.Phoenix.Ecto.CheckRepoStatus','check_pending_migrations!',2,[{file,"lib/phoenix_ecto/check_repo_status.ex"},{line,67}]},{'Elixir.Phoenix.Ecto.CheckRepoStatus','-call/2-fun-0-',3,[{file,"lib/phoenix_ecto/check_repo_status.ex"},{line,27}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,2111}]},{'Elixir.Phoenix.Ecto.CheckRepoStatus',call,...},...]},...},...},...}
2020-11-01 15:20:16.068 [error] <0.605.0> Cowboy stream 2 with ranch listener 'Elixir.ProductsWeb.Endpoint.HTTP' and connection process <0.596.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Ecto.PendingMigrationError',repo => 'Elixir.Products.Repo'},[{'Elixir.Phoenix.Ecto.CheckRepoStatus','check_pending_migrations!',2,[{file,"lib/phoenix_ecto/check_repo_status.ex"},{line,67}]},{'Elixir.Phoenix.Ecto.CheckRepoStatus','-call/2-fun-0-',3,[{file,"lib/phoenix_ecto/check_repo_status.ex"},{line,27}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,2111}]},{'Elixir.Phoenix.Ecto.CheckRepoStatus',call,...},...]},...},...}
2020-11-01 15:22:01.934 [error] <0.557.0> gen_server 'Elixir.Messages' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer Messages but no handle_call/3 clause was provided">>} in 'Elixir.Rabbitmq.Consumer':handle_call/3 line 773
2020-11-01 15:22:01.962 [error] <0.557.0> CRASH REPORT Process 'Elixir.Messages' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer Messages but no handle_call/3 clause was provided">>} in 'Elixir.Rabbitmq.Consumer':handle_call/3 line 773
2020-11-01 15:22:01.963 [error] <0.408.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Rabbitmq.Consumer' started with 'Elixir.Rabbitmq.Consumer':start_link([]) at <0.557.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer Messages but no handle_call/3 clause was provided">>} in 'Elixir.Rabbitmq.Consumer':handle_call/3 line 773 in context child_terminated
2020-11-01 15:22:02.066 [error] <0.585.0> CRASH REPORT Process <0.585.0> with 0 neighbours exited with reason: {{{{{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer Messages but no handle_call/3 clause was provided">>},[{'Elixir.Rabbitmq.Consumer',handle_call,3,[{file,"lib/gen_server.ex"},{line,773}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,['Elixir.Messages',get,...]}},...},...},...}
2020-11-01 15:22:02.076 [error] <0.585.0> Cowboy stream 1 with ranch listener 'Elixir.ProductsWeb.Endpoint.HTTP' and connection process <0.584.0> had its request process exit with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer Messages but no handle_call/3 clause was provided">>},[{'Elixir.Rabbitmq.Consumer',handle_call,3,[{file,"lib/gen_server.ex"},{line,773}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,['Elixir.Messages',get,5000]}},...},...}
2020-11-01 15:30:43.186 [error] <0.600.0> gen_server 'Elixir.Messages' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer Messages but no handle_call/3 clause was provided">>} in 'Elixir.Rabbitmq.Consumer':handle_call/3 line 773
2020-11-01 15:30:43.188 [error] <0.600.0> CRASH REPORT Process 'Elixir.Messages' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer Messages but no handle_call/3 clause was provided">>} in 'Elixir.Rabbitmq.Consumer':handle_call/3 line 773
2020-11-01 15:30:43.189 [error] <0.408.0> Supervisor 'Elixir.Products.Supervisor' had child 'Elixir.Rabbitmq.Consumer' started with 'Elixir.Rabbitmq.Consumer':start_link([]) at <0.600.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer Messages but no handle_call/3 clause was provided">>} in 'Elixir.Rabbitmq.Consumer':handle_call/3 line 773 in context child_terminated
2020-11-01 15:30:43.207 [error] <0.568.0> gen_server <0.568.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-11-01 15:30:43.208 [error] <0.568.0> CRASH REPORT Process <0.568.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-11-01 15:30:43.208 [error] <0.567.0> Supervisor {<0.567.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:46689 -> 127.0.0.1:5672">>,1}) at <0.568.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-11-01 15:30:43.208 [error] <0.567.0> Supervisor {<0.567.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:46689 -> 127.0.0.1:5672">>,1}) at <0.568.0> exit with reason reached_max_restart_intensity in context shutdown
2020-11-01 15:30:43.216 [error] <0.653.0> CRASH REPORT Process <0.653.0> with 0 neighbours exited with reason: {{{{{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer Messages but no handle_call/3 clause was provided">>},[{'Elixir.Rabbitmq.Consumer',handle_call,3,[{file,"lib/gen_server.ex"},{line,773}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,['Elixir.Messages',get,...]}},...},...},...}
2020-11-01 15:30:43.217 [error] <0.653.0> Cowboy stream 1 with ranch listener 'Elixir.ProductsWeb.Endpoint.HTTP' and connection process <0.652.0> had its request process exit with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to call GenServer Messages but no handle_call/3 clause was provided">>},[{'Elixir.Rabbitmq.Consumer',handle_call,3,[{file,"lib/gen_server.ex"},{line,773}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,706}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,735}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]},{'Elixir.GenServer',call,['Elixir.Messages',get,5000]}},...},...}
2020-11-01 15:32:35.764 [error] <0.611.0> gen_server <0.611.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-11-01 15:32:35.764 [error] <0.611.0> CRASH REPORT Process <0.611.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-11-01 15:32:35.764 [error] <0.610.0> Supervisor {<0.610.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:40429 -> 127.0.0.1:5672">>,1}) at <0.611.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-11-01 15:32:35.764 [error] <0.610.0> Supervisor {<0.610.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:40429 -> 127.0.0.1:5672">>,1}) at <0.611.0> exit with reason reached_max_restart_intensity in context shutdown
2020-11-01 15:52:37.981 [error] <0.603.0> CRASH REPORT Process <0.603.0> with 0 neighbours exited with reason: {{{{noproc,{'Elixir.GenServer',call,['Elixir.Messages',get,5000]}},{'Elixir.ProductsWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"postman-token">> => <<"fd5f709d-553b-46c2-a8b9-5107237e48f8">>,<<"token">> => <<"...">>,...},...}},...},...]}},...},...}
2020-11-01 15:52:37.989 [error] <0.603.0> Cowboy stream 1 with ranch listener 'Elixir.ProductsWeb.Endpoint.HTTP' and connection process <0.602.0> had its request process exit with reason: {{{noproc,{'Elixir.GenServer',call,['Elixir.Messages',get,5000]}},{'Elixir.ProductsWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"postman-token">> => <<"fd5f709d-553b-46c2-a8b9-5107237e48f8">>,<<"token">> => <<"...">>,...},...}},...},...]}},...}
2020-11-01 16:04:02.465 [error] <0.567.0> Supervisor {<0.567.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.560.0>, 1, <0.568.0>, {<<"client 127.0.0.1:51333 -> 127.0.0.1:5672">>,1}) at <0.569.0> exit with reason {shutdown,{connection_closing,{server_initiated_close,320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>}}} in context shutdown_error
2020-11-01 16:27:07.453 [error] <0.604.0> CRASH REPORT Process <0.604.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    ...">>,...},...},...},...},...}
2020-11-01 16:27:07.460 [error] <0.604.0> Cowboy stream 1 with ranch listener 'Elixir.ProductsWeb.Endpoint.HTTP' and connection process <0.603.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    @d...">>,...},...},...},...}
2020-11-01 16:33:00.383 [error] <0.596.0> CRASH REPORT Process <0.596.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    ...">>,...},...},...},...},...}
2020-11-01 16:33:00.390 [error] <0.596.0> Cowboy stream 1 with ranch listener 'Elixir.ProductsWeb.Endpoint.HTTP' and connection process <0.595.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    @d...">>,...},...},...},...}
2020-11-01 16:41:43.156 [error] <0.577.0> CRASH REPORT Process <0.577.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Ecto.PendingMigrationError',repo => 'Elixir.Products.Repo'},[{'Elixir.Phoenix.Ecto.CheckRepoStatus','check_pending_migrations!',2,[{file,"lib/phoenix_ecto/check_repo_status.ex"},{line,67}]},{'Elixir.Phoenix.Ecto.CheckRepoStatus','-call/2-fun-0-',3,[{file,"lib/phoenix_ecto/check_repo_status.ex"},{line,27}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,2111}]},{'Elixir.Phoenix.Ecto.CheckRepoStatus',call,...},...]},...},...},...}
2020-11-01 16:41:43.164 [error] <0.577.0> Cowboy stream 1 with ranch listener 'Elixir.ProductsWeb.Endpoint.HTTP' and connection process <0.576.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Ecto.PendingMigrationError',repo => 'Elixir.Products.Repo'},[{'Elixir.Phoenix.Ecto.CheckRepoStatus','check_pending_migrations!',2,[{file,"lib/phoenix_ecto/check_repo_status.ex"},{line,67}]},{'Elixir.Phoenix.Ecto.CheckRepoStatus','-call/2-fun-0-',3,[{file,"lib/phoenix_ecto/check_repo_status.ex"},{line,27}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,2111}]},{'Elixir.Phoenix.Ecto.CheckRepoStatus',call,...},...]},...},...}
